apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
    {{- include "shared.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
      - port: {{ .Values.service.port }}
        targetPort: web-auth
        protocol: TCP
        name: web-auth
        {{- if eq .Values.service.type "NodePort" }}
        nodePort: {{ .Values.service.nodePort }}
        {{- end }}
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
