---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-web-auth
  labels:
    {{- include "service.labels" . | nindent 4 }}
    {{- include "shared.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "web-auth/*").AsConfig | indent 2 }}
